<div class="row">
    <form class="form-horizontal" id="edit-form" action="/admin/tag/edit" method="POST">
        <div class="form-group">
            <label for="field-title" class="col-sm-2">分类</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="tag_name" value="<?= $info['tag_name']; ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label for="field-api" class="col-sm-2">封面图地址</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="cover" placeholder="地址" value="<?= $info['cover']; ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label for="field-api" class="col-sm-2">描述</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="intro" placeholder="描述" value="<?= $info['intro']; ?>"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="text" class="hide" name="tag_id" value="<?= $info['tag_id']; ?>">
                <button type="submit" name="submit" value="1" class="btn btn-info">保存</button>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $("#edit-form").myAjaxForm();
    })
</script>