<div class="btn-group">
    <button type="button" class="btn btn-success" data-remote="/admin/tag/add?is_ajax=0" data-toggle="modal">新建
    </button>
</div>
<p></p>
<table class="table table-bordered col-lg-12">
    <tr>
        <th>ID</th>
        <th class="col-lg-1">封面图</th>
        <th>分类</th>
        <th>视频数量</th>
        <th>简介</th>
        <th>时间</th>
        <th>操作</th>
    </tr>
    <?php if ($data): ?>
        <?php foreach ($data as $row): ?>
            <tr data-id="<?= $row['tag_id']; ?>">
                <td><?= $row['tag_id']; ?></td>
                <td><img src="<?= $row['cover'] ? R . $row['cover'] : ''; ?>"/></td>
                <td><?= $row['tag_name']; ?></td>
                <td><?= $row['video_num']; ?></td>
                <td><?= $row['intro']; ?></td>
                <td>
                    创建：<?= date('Y-m-d H:i:s', $row['create_time']); ?><br/>
                    修改：<?= date('Y-m-d H:i:s', $row['update_time']); ?><br/>
                </td>
                <td>
                    <a data-remote="/admin/tag/edit?is_ajax=0&tag_id=<?= $row['tag_id']; ?>" data-toggle="modal">编辑</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>
<script>
    $(function () {
        $('.js-del').click(function () {
            if (!confirm('确定删除?')) {
                return false;
            }
            var id = $(this).parents('tr').data('id');
            $.myAjaxPost('/admin/video/del', {video_id: id});
        })
    });
</script>