<div class="btn-group">
    <button type="button" class="btn btn-success" data-remote="/admin/resource/uploadImage?is_ajax=0" data-toggle="modal">新建
    </button>
</div>
<p></p>
<table class="table table-bordered col-lg-12">
    <tr>
        <th>ID</th>
        <th class="col-lg-2">资源</th>
        <th>资源地址</th>
        <th>操作</th>
    </tr>
    <?php if ($data): ?>
        <?php foreach ($data as $row): ?>
            <tr data-id="<?= $row['id']; ?>">
                <td><?= $row['id']; ?></td>
                <td><img src="<?= r() . $row['url']; ?>"/></td>
                <td><?= $row['url']; ?></td>
                <td>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>
<script>
    $(function () {
        $('.js-del').click(function () {
            if (!confirm('确定删除?')) {
                return false;
            }
            var id = $(this).parents('tr').data('id');
            $.myAjaxPost('/admin/video/del', {video_id: id});
        })
    });
</script>