<link rel="stylesheet" href="<?= r(); ?>css/zui.uploader.min.css">
<script src="<?= r(); ?>js/zui.uploader.min.js"></script>
<div class="row">
    <form class="form-horizontal">
        <div class="form-group">
        </div>
        <div class="form-group">
            <label for="field-remark" class="col-sm-2">封面图上传</label>
            <div class="col-sm-8">
                <div id="uploader-img" class="uploader">
                    <div class="file-list" data-drag-placeholder="请拖拽文件到此处"></div>
                    <button type="button" class="btn btn-primary uploader-btn-browse"><i
                                class="icon icon-cloud-upload"></i> 选择文件
                    </button>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="field-remark" class="col-sm-2">资源地址</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="js-img-src" value="" readonly>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $('#uploader-img').uploader({
            autoUpload: true,            // 当选择文件后立即自动进行上传操作
            url: '/admin/resource/uploadImage?is_ajax=1',  // 文件上传提交地址
            filters: {
                mime_types: [
                    {title: '图片', extensions: 'jpg,png'}
                ],
                // 不允许上传重复文件
                prevent_duplicates: true
            },
            chunk_size: 0,
            responseHandler: function (responseObject) {
                var res = JSON.parse(responseObject.response);
                if (+res.code !== 0) {
                    alert(res.msg);
                } else {
                    $("#js-img-src").val(res.result.uri);
                }
            }
        });
    })
</script>