<link rel="stylesheet" href="<?= r(); ?>css/zui.uploader.min.css">
<script src="<?= r(); ?>js/zui.uploader.min.js"></script>
<div class="row">
    <form class="form-horizontal" id="save-form" action="/admin/video/save" method="POST">
        <div class="form-group">
        </div>
        <?php if (!$video_id): ?>
            <div class="form-group">
                <label for="field-remark" class="col-sm-2">视频上传</label>
                <div class="col-sm-8">
                    <div id="uploader" class="uploader">
                        <div class="file-list" data-drag-placeholder="请拖拽文件到此处"></div>
                        <button type="button" class="btn btn-primary uploader-btn-browse"><i
                                    class="icon icon-cloud-upload"></i> 选择文件
                        </button>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="<?= $video_id ? '' : 'hide'; ?>" id="js-info">
            <div class="form-group">
                <label for="field-remark" class="col-sm-2">封面图上传</label>
                <div class="col-sm-8">
                    <div id="uploader-cover" class="uploader">
                        <div class="file-list" data-drag-placeholder="请拖拽文件到此处"></div>
                        <button type="button" class="btn btn-primary uploader-btn-browse"><i
                                    class="icon icon-cloud-upload"></i> 选择文件
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="field-remark" class="col-sm-2">简介</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="intro" value="<?= $video['intro']; ?>"
                           placeholder="视频简介200字以内"/>
                </div>
            </div>
            <div class="form-group">
                <label for="field-remark" class="col-sm-2">时长</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="time_length" value="<?= $video['time_length']; ?>"
                           placeholder="如：00:15"/>
                </div>
            </div>
            <div class="form-group">
                <label for="field-remark" class="col-sm-2">分类标签</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="tag_str" value="<?= $video['tag_str']; ?>"
                           placeholder="分类，多个分类以逗号','分隔"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input class="hide" name="video_id" id="js-video-id" value="<?= $video_id; ?>"/>
                    <button type="submit" class="btn btn-info">保存</button>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $("#save-form").myAjaxForm();

        $('#uploader').uploader({
            autoUpload: true,            // 当选择文件后立即自动进行上传操作
            url: '/admin/video/add',  // 文件上传提交地址
            filters: {
                mime_types: [
                    {title: '视频', extensions: 'mp4'}
                ],
                // 不允许上传重复文件
                prevent_duplicates: true
            },
            limitFilesCount: 1,
            chunk_size: 0,
            responseHandler: function (responseObject) {
                var res = JSON.parse(responseObject.response);
                if (+res.code !== 0) {
                    alert(res.msg);
                } else {
                    $("#js-info").removeClass('hide');
                    $("#js-video-id").val(res.result.video_id);
                }
            }
        });
        $('#uploader-cover').uploader({
            autoUpload: true,            // 当选择文件后立即自动进行上传操作
            url: '/admin/video/save',  // 文件上传提交地址
            filters: {
                mime_types: [
                    {title: '封面图', extensions: 'jpg,png'}
                ],
                // 不允许上传重复文件
                prevent_duplicates: true
            },
            limitFilesCount: 1,
            chunk_size: 0,
            multipart_params: function () {
                return {
                    video_id: $("#js-video-id").val(),
                    cover: 1
                };
            },
            responseHandler: function (responseObject) {
                var res = JSON.parse(responseObject.response);
                if (+res.code !== 0) {
                    alert(res.msg);
                }
            }
        });
    })
</script>