<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="renderer" content="webkit"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link rel="stylesheet" href="<?= r(); ?>css/zui.min.css">
    <link rel="stylesheet" href="<?= r(); ?>css/main.min.css">
    <link rel="stylesheet" href="<?= r(); ?>css/admin.css">
    <title>视频制作大师平台</title>

    <script src="<?= r(); ?>js/main.min.js"></script>
    <script src="<?= r(); ?>js/jquery.form.js"></script>
    <script src="<?= r(); ?>js/my.admin.js"></script>
</head>

<body>
<!-- 整体布局 Start -->
<div id="mat-layout" class="min-width header-fixed footer-fixed side-fixed _side-fixed _side-narrow">

    <!-- 顶栏 Start -->
    <header id="mat-header">
        <a href="/" class="pull-left" id="mat-brand">
            <div class="brand-title">
                <div class="brand-text">视频制作大师平台</div>
            </div>
        </a>
        <nav id="mat-header-nav" data-dropdown="hover">
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown">
                    <a data-remote="/admin/resource/uploadImage?is_ajax=0" data-toggle="modal">
                        <i class="icon icon-file-image"></i>
                        <span class="text">上传图片</span>
                    </a>
                </li>
                <!--<li class="dropdown">
                    <a href="#" data-toggle="dropdown">
                        <i class="icon icon-globe"></i>
                        <span class="text">简体中文</span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">简体中文</a></li>
                        <li><a href="#">繁体中文</a></li>
                        <li><a href="#">English</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon icon-user"></i>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">账号信息</a></li>
                        <li><a href="#">修改密码</a></li>
                        <li class="divider"></li>
                        <li><a href="/logout">退出</a></li>
                    </ul>
                </li>-->
            </ul>

        </nav>
    </header>
    <!-- 顶栏 End -->
    <!-- 中间容器层 Start -->
    <div id="mat-container">

        <!-- 左侧边栏 Start -->
        <div id="mat-side" class="scrollbar-hover" style="max-height: 1000px; overflow: scroll;">
            <!-- 左侧导航菜单 Start -->
            <nav class="menu" data-toggle="menu" id="mat-nav">
                <ul class="nav">
                    <li class="header">菜单分类</li>
                    <?php foreach ($menu as $controller => $info): ?>
                        <li class="nav-parent<?= $_c == $controller ? ' show' : ''; ?>">
                            <a href="<?= is_array($info['action']) ? 'javascript:;' : '/admin/' . $controller . '/' . $info['action']; ?>">
                                <i class="icon <?= $info['icon']; ?>"></i>
                                <span class="title"><?= $info['name']; ?></span>
                            </a>
                            <?php if (is_array($info['action'])): ?>
                                <ul class="nav">
                                    <?php foreach ($info['action'] as $action => $name): ?>
                                        <li class="">
                                            <a href="/admin/<?= $controller . '/' . $action; ?>">
                                                <span class="title"><?= $name; ?></span>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </nav>
            <!-- 左侧导航菜单 End -->
        </div>
        <!-- 左侧边栏 End -->

        <!-- 主容器层 Start -->
        <div id="mat-main">
