<div class="row">
    <form class="form-horizontal" id="add-form" action="/admin/config/add" method="POST">
        <div class="form-group">
            <label for="field-title" class="col-sm-2">KEY</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="key" placeholder="配置键名"/>
            </div>
        </div>
        <div class="form-group">
            <label for="field-api" class="col-sm-2">描述</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="intro" value=""/>
            </div>
        </div>
        <div class="form-group">
            <label for="field-api" class="col-sm-2">值</label>
            <div class="col-sm-8">
                <textarea class="form-control" name="value" rows="5"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" name="submit" value="1" class="btn btn-info">添加</button>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $("#add-form").myAjaxForm();
    })
</script>