<div class="row">
    <form class="form-horizontal" id="edit-form" action="/admin/config/edit" method="POST">
        <div class="form-group">
            <label for="field-title" class="col-sm-2">KEY</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="key" placeholder="配置键名" value="<?= $info['key']; ?>"
                       disabled/>
            </div>
        </div>
        <div class="form-group">
            <label for="field-api" class="col-sm-2">描述</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" name="intro" placeholder="描述" value="<?= $info['intro']; ?>"/>
            </div>
        </div>
        <div class="form-group">
            <label for="field-api" class="col-sm-2">值</label>
            <div class="col-sm-8">
                <textarea class="form-control" name="value" rows="5" placeholder="值"><?= $info['value']; ?></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="text" class="hide" name="id" value="<?= $info['id']; ?>">
                <input type="text" class="hide" name="row" value="<?= $row; ?>">
                <button type="submit" name="submit" value="1" class="btn btn-info">保存</button>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $("#edit-form").myAjaxForm();
    })
</script>